import { FormEvent, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

const input = "w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-400";

export default function CoordinatorManagement() {
  const [, setLocation] = useLocation();
  const eventId = useMemo(() => Number(new URLSearchParams(window.location.search).get("eventId")), []);
  const staff = trpc.edStaff.access.useQuery(undefined, { retry: false });
  const invitations = trpc.coordinator.invitations.list.useQuery({ eventId }, { enabled: Boolean(eventId && staff.data) });
  const submissions = trpc.coordinator.submissions.listForEvent.useQuery({ eventId }, { enabled: Boolean(eventId && staff.data) });
  const create = trpc.coordinator.invitations.create.useMutation({ onSuccess: () => void invitations.refetch() });
  const revoke = trpc.coordinator.invitations.revoke.useMutation({ onSuccess: () => void invitations.refetch() });
  const ready = trpc.coordinator.submissions.markReadyForInitialImport.useMutation({ onSuccess: () => void submissions.refetch() });
  const [recipientName, setRecipientName] = useState("");
  const [recipientEmail, setRecipientEmail] = useState("");
  const [leagueSessions, setLeagueSessions] = useState("");
  const [issuedCode, setIssuedCode] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); const value = await create.mutateAsync({ eventId, recipientName: recipientName || undefined, recipientEmail: recipientEmail || undefined, leagueSessions: leagueSessions.split(",").map((item) => item.trim()).filter(Boolean) }); setIssuedCode(value.code); setRecipientName(""); setRecipientEmail(""); setLeagueSessions(""); };
  if (!eventId) return <main className="min-h-screen bg-[#071018] p-8 text-slate-100"><p>Choose an event from the Event Director Portal before opening coordinator management.</p><button className="mt-4 rounded-lg bg-cyan-400 px-4 py-2 font-bold text-slate-950" onClick={() => setLocation("/ed")}>Return to Event Director Portal</button></main>;
  if (staff.isLoading) return <main className="min-h-screen grid place-items-center bg-[#071018] text-slate-100">Checking secure Event Director access…</main>;
  if (!staff.data) return <main className="min-h-screen grid place-items-center bg-[#071018] text-slate-100">Event Director sign-in is required.</main>;
  return <main className="min-h-screen bg-[#071018] px-4 py-8 text-slate-100 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap justify-between gap-4 border-b border-slate-800 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Event Director · Coordinator Package</p><h1 className="mt-2 text-3xl font-bold">Coordinator invitations & roster audit</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Invite a center coordinator with a 72-hour single-use code. Coordinators supply data; you audit and prepare it for the Owner’s import.</p></div><button onClick={() => setLocation("/ed")} className="rounded-lg border border-slate-600 px-3 py-2 text-sm">Back to ED Portal</button></header>
  <div className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-cyan-400/20 bg-slate-900 p-5"><h2 className="text-lg font-bold">Issue coordinator invitation</h2><form onSubmit={submit} className="mt-4 grid gap-3"><input className={input} value={recipientName} onChange={(e) => setRecipientName(e.target.value)} placeholder="Coordinator name (optional)"/><input className={input} type="email" value={recipientEmail} onChange={(e) => setRecipientEmail(e.target.value)} placeholder="Coordinator email (optional)"/><input className={input} value={leagueSessions} onChange={(e) => setLeagueSessions(e.target.value)} placeholder="League times, comma separated"/><button disabled={create.isPending} className="rounded-lg bg-cyan-400 px-4 py-3 font-bold text-slate-950 disabled:opacity-50">Generate 72-hour invitation</button>{create.error && <p className="text-sm text-rose-300">{create.error.message}</p>}</form>{issuedCode && <div className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-500/10 p-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-300">Share once with this coordinator</p><code className="mt-2 block break-all text-xl font-bold text-emerald-100">{issuedCode}</code><p className="mt-2 text-xs text-slate-300">It expires in 72 hours and becomes invalid after redemption.</p></div>}</section>
  <section className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-lg font-bold">Invitation status</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="p-2">Coordinator</th><th className="p-2">Center</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody>{invitations.data?.map((invite: any) => <tr key={invite.id} className="border-t border-slate-800"><td className="p-2">{invite.recipientName || invite.recipientEmail || "Unassigned"}</td><td className="p-2">{invite.centerName || "Any center"}</td><td className="p-2">{invite.redeemedAt ? "Redeemed" : invite.revokedAt ? "Revoked" : "Pending"}</td><td className="p-2">{!invite.redeemedAt && !invite.revokedAt && <button onClick={() => revoke.mutate({ invitationId: invite.id })} className="text-rose-300 underline">Revoke</button>}</td></tr>)}</tbody></table></div></section></div>
  <section className="mt-6 rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-lg font-bold">Coordinator roster submissions</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="p-2">Coordinator</th><th className="p-2">Center</th><th className="p-2">Rows</th><th className="p-2">Status</th><th className="p-2">Review</th></tr></thead><tbody>{submissions.data?.map((submission: any) => <tr key={submission.id} className="border-t border-slate-800"><td className="p-2">{submission.firstName} {submission.lastName}<span className="block text-xs text-slate-400">{submission.email}</span></td><td className="p-2">{submission.centerName || "Unassigned"}</td><td className="p-2">{submission.rowCount}</td><td className="p-2">{submission.status}</td><td className="p-2">{submission.status === "draft" && <button onClick={() => ready.mutate({ submissionId: submission.id })} className="rounded bg-emerald-500/20 px-2 py-1 text-emerald-200">Ready for Owner</button>}</td></tr>)}</tbody></table></div></section></div></main>;
}
