import { FormEvent, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

const shell = "min-h-screen bg-[#071018] px-4 py-8 text-slate-100 sm:px-8";
const input = "w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-cyan-400";

export default function CoordinatorPortal() {
  const [, setLocation] = useLocation();
  const access = trpc.coordinator.access.useQuery();
  const scopes = trpc.coordinator.myScopes.useQuery(undefined, { enabled: Boolean(access.data) });
  const logout = trpc.coordinator.logout.useMutation({ onSuccess: () => { void access.refetch(); void scopes.refetch(); } });
  const login = trpc.coordinator.login.useMutation({ onSuccess: () => { void access.refetch(); void scopes.refetch(); } });
  const redeem = trpc.coordinator.redeem.useMutation({ onSuccess: () => setLocation("/coordinator") });
  const [mode, setMode] = useState<"login" | "redeem">("login");
  const [form, setForm] = useState<Record<string, string>>({ preferredContactMethod: "Mobile" });
  const update = (key: string, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault();
    if (mode === "login") login.mutate({ email: form.email ?? "", password: form.password ?? "" });
    else redeem.mutate({ code: form.code ?? "", firstName: form.firstName ?? "", lastName: form.lastName ?? "", email: form.email ?? "", password: form.password ?? "", centerPhone: form.centerPhone ?? "", centerExtension: form.centerExtension ?? "", mobilePhone: form.mobilePhone || undefined, preferredContactMethod: form.preferredContactMethod || undefined });
  };
  if (access.isLoading) return <main className={`${shell} grid place-items-center`}>Checking secure coordinator access…</main>;
  if (!access.data) return <main className={shell}><section className="mx-auto max-w-xl rounded-2xl border border-cyan-400/20 bg-slate-900/80 p-6 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Bowl Vegas · Coordinator Package</p><h1 className="mt-2 text-3xl font-bold">Coordinator workspace</h1><p className="mt-3 text-sm leading-6 text-slate-300">Use the one-time invitation code sent by your Event Director to create your coordinator account. Returning coordinators may sign in with their email and password.</p><div className="mt-6 flex gap-2"><button onClick={() => setMode("login")} className={`rounded-lg px-4 py-2 text-sm font-bold ${mode === "login" ? "bg-cyan-400 text-slate-950" : "bg-slate-800"}`}>Sign in</button><button onClick={() => setMode("redeem")} className={`rounded-lg px-4 py-2 text-sm font-bold ${mode === "redeem" ? "bg-cyan-400 text-slate-950" : "bg-slate-800"}`}>Use invitation</button></div><form onSubmit={submit} className="mt-5 grid gap-3">{mode === "redeem" && <><input className={input} placeholder="One-time invitation code" onChange={(e) => update("code", e.target.value)} required /><div className="grid gap-3 sm:grid-cols-2"><input className={input} placeholder="First name" onChange={(e) => update("firstName", e.target.value)} required /><input className={input} placeholder="Last name" onChange={(e) => update("lastName", e.target.value)} required /></div></>}<input className={input} type="email" placeholder="Email address (your username)" onChange={(e) => update("email", e.target.value)} required /><input className={input} type="password" placeholder="Password" onChange={(e) => update("password", e.target.value)} required />{mode === "redeem" && <><div className="grid gap-3 sm:grid-cols-2"><input className={input} placeholder="Center phone number" onChange={(e) => update("centerPhone", e.target.value)} required /><input className={input} placeholder="Extension" onChange={(e) => update("centerExtension", e.target.value)} required /></div><input className={input} placeholder="Mobile or direct number (optional)" onChange={(e) => update("mobilePhone", e.target.value)} /><select className={input} value={form.preferredContactMethod} onChange={(e) => update("preferredContactMethod", e.target.value)}><option>Mobile</option><option>Center phone</option><option>Email</option></select></>}<button disabled={login.isPending || redeem.isPending} className="rounded-lg bg-cyan-400 px-4 py-3 font-bold text-slate-950 disabled:opacity-50">{mode === "login" ? "Sign in securely" : "Create coordinator account"}</button>{(login.error || redeem.error) && <p className="text-sm text-rose-300">{login.error?.message ?? redeem.error?.message}</p>}</form></section></main>;
  return <main className={shell}><section className="mx-auto max-w-4xl"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-800 pb-6"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Coordinator workspace</p><h1 className="mt-2 text-3xl font-bold">Welcome, {access.data.firstName ?? "Coordinator"}</h1><p className="mt-2 text-slate-300">Provide and complete your roster data. Your Event Director can audit its status; only the Owner performs app imports and generated data.</p></div><button onClick={() => logout.mutate()} className="rounded-lg border border-slate-600 px-3 py-2 text-sm">Sign out</button></header><div className="mt-6 grid gap-4 md:grid-cols-2">{scopes.data?.map((scope: any) => <article key={scope.id} className="rounded-xl border border-slate-700 bg-slate-900 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-cyan-300">Authorized scope</p><h2 className="mt-2 text-xl font-bold">{scope.eventName}</h2><p className="mt-1 text-sm text-slate-300">{scope.centerName ?? "Center scope pending"} · {scope.eventYear}</p><p className="mt-4 rounded-lg bg-slate-950 p-3 text-sm text-slate-300">Your roster intake and review checklist will appear here. You may return to complete information after the initial roster is accepted.</p></article>)}</div>{scopes.data?.length === 0 && <p className="mt-8 rounded-xl border border-amber-300/30 bg-amber-500/10 p-5 text-amber-100">Your account is active but has no current event scope. Contact your Event Director.</p>}</section></main>;
}
