import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";
import { CenterBulletinBoard } from "@/components/CenterBulletinBoard";

export function BulletinModerationPanel({ eventId }: { eventId?: number }) {
  const utils = trpc.useUtils();
  const centers = trpc.bulletin.eventCenters.useQuery({ eventId: eventId ?? 0 }, { enabled: Boolean(eventId) });
  const [centerId, setCenterId] = useState<number | undefined>();
  const reports = trpc.bulletin.listReports.useQuery({ eventId: eventId ?? 0 }, { enabled: Boolean(eventId) });
  const resolve = trpc.bulletin.resolveReport.useMutation({ onSuccess: async () => { await utils.bulletin.listReports.invalidate(); } });
  useEffect(() => { if (!centerId && centers.data?.[0]?.id) setCenterId(Number(centers.data[0].id)); }, [centerId, centers.data]);
  if (!eventId) return null;
  return <section className="space-y-5"><section className="rounded-2xl border border-violet-300/20 bg-slate-950/65 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">Bulletin oversight</p><h2 className="mt-1 text-xl font-semibold text-white">Moderate the attendee board by center</h2><p className="mt-1 text-sm text-slate-400">Event staff can review, hide, restore, pin, and lock posts. Participant names and contact details are not surfaced on the board.</p></div><label className="grid gap-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Center<select value={centerId ?? ""} onChange={(event) => setCenterId(Number(event.target.value))} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm normal-case text-white"><option value="" disabled>Select a center</option>{centers.data?.map((center: any) => <option key={center.id} value={center.id}>{center.centerName}</option>)}</select></label></div></section>{centerId && <CenterBulletinBoard eventId={eventId} centerId={centerId} canModerate />}{reports.data?.length ? <section className="rounded-2xl border border-rose-300/20 bg-slate-950/65 p-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-rose-200">Open reports</p><h3 className="mt-1 text-lg font-semibold text-white">Content requiring review</h3></div><div className="mt-4 space-y-3">{reports.data.map((report: any) => <article key={report.id} className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold capitalize text-white">{report.category} report</p><p className="mt-1 text-sm text-slate-300">{report.businessName ?? report.postBody ?? "Reported item"}</p>{report.note && <p className="mt-2 text-xs text-slate-500">Reporter note: {report.note}</p>}</div><button onClick={() => resolve.mutate({ eventId, reportId: report.id })} disabled={resolve.isPending} className="rounded-lg border border-emerald-300/30 px-3 py-2 text-sm font-semibold text-emerald-100 disabled:opacity-50">Resolve</button></div></article>)}</div></section> : null}{reports.error && <p className="rounded-lg border border-rose-400/30 bg-rose-500/10 p-3 text-sm text-rose-100">{reports.error.message}</p>}</section>;
}
